import type { FeatureClass, FeatureStatus } from '../dto';
import type { UserRole } from '../enums';

/**
 * Feature Registry (addendum §12, §36, §37) — the single code-level source of
 * truth for what the platform can do. The Platform & API admin views, the
 * Mobile Readiness dashboard, GET /api/v1/platform/* and the generated
 * docs/FEATURE_MATRIX.md all derive from THIS list, so nothing goes stale.
 *
 * "Mobile Ready" is not a database fact — a feature is mobile-ready only when
 * its business logic is server-side, an API endpoint exists and is documented,
 * auth + permissions are enforced server-side, contracts are stable, media is
 * represented independently of the Web UI, and filtering/pagination are
 * server-side (§37). We set `mobileReady` accordingly, honestly.
 */

export interface FeatureEntry {
  key: string;
  name: string;
  description: string;
  module: string;
  classification: FeatureClass;
  apiStatus: FeatureStatus;
  webStatus: FeatureStatus;
  mobileReady: boolean;
  permissions: UserRole[];
  flag: string | null;
  minApiVersion: string;
  apiEndpoints: string[];
  deepLink: string | null;
}

const ALL: UserRole[] = ['ADMIN', 'STAFF'];
const ADMIN_ONLY: UserRole[] = ['ADMIN'];

export const FEATURES: FeatureEntry[] = [
  {
    key: 'auth',
    name: 'Authentication',
    description: 'Login, token refresh, current user, logout, device sessions.',
    module: 'Auth',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'POST /api/v1/auth/login',
      'POST /api/v1/auth/refresh',
      'POST /api/v1/auth/logout',
      'POST /api/v1/auth/change-password',
      'GET /api/v1/auth/me',
      'PATCH /api/v1/auth/me/preferences',
      'GET /api/v1/auth/sessions',
    ],
    deepLink: null,
  },
  {
    key: 'brands',
    name: 'Brands & Brand Switching',
    description: 'Multi-brand workspaces, brand CRUD and brand-scoped views.',
    module: 'Brands',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/brands',
      'POST /api/v1/brands',
      'GET /api/v1/brands/:id',
      'PATCH /api/v1/brands/:id',
      'GET /api/v1/brands/:id/dashboard',
    ],
    deepLink: '/brands/:slug',
  },
  {
    key: 'influencers',
    name: 'Influencer Management',
    description: 'Directory, add-from-URL, 360 profile, social accounts, notes, tags, brand relationships.',
    module: 'Influencers',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/influencers',
      'GET /api/v1/influencers/export',
      'POST /api/v1/influencers',
      'GET /api/v1/influencers/:id',
      'PATCH /api/v1/influencers/:id',
      'POST /api/v1/influencers/resolve',
      'GET /api/v1/influencers/:id/followers',
      'GET /api/v1/influencers/:id/audience-health',
    ],
    deepLink: '/influencers/:id',
  },
  {
    key: 'social_accounts',
    name: 'Social Accounts & Metrics',
    description: 'Per-network accounts, follower history snapshots, provenance.',
    module: 'Metrics',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'POST /api/v1/influencers/:id/social-accounts',
      'PATCH /api/v1/social-accounts/:id',
      'POST /api/v1/social-accounts/:id/sync',
    ],
    deepLink: null,
  },
  {
    key: 'campaigns',
    name: 'Campaign Management',
    description: 'Campaign CRUD, workspace, progress, influencers, statuses.',
    module: 'Campaigns',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/campaigns',
      'POST /api/v1/campaigns',
      'GET /api/v1/campaigns/:id',
      'PATCH /api/v1/campaigns/:id',
      'POST /api/v1/campaigns/:id/influencers',
    ],
    deepLink: '/campaigns/:id',
  },
  {
    key: 'deliverables',
    name: 'Deliverables',
    description: 'Per-influencer deliverables, statuses, requirements, publish links.',
    module: 'Deliverables',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'POST /api/v1/campaign-influencers/:id/deliverables',
      'PATCH /api/v1/deliverables/:id',
    ],
    deepLink: null,
  },
  {
    key: 'submissions',
    name: 'Deliverable Submissions & Review',
    description: 'UGC/draft submission, threaded review (approve / request changes / reject); UGC deliverables complete without any public URL.',
    module: 'Deliverables',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/deliverables/:id/submissions',
      'POST /api/v1/deliverables/:id/submissions',
      'GET /api/v1/submissions/:id',
      'POST /api/v1/submissions/:id/review',
      'POST /api/v1/submissions/:id/comments',
      'GET /api/v1/campaigns/:id/submissions',
    ],
    deepLink: null,
  },
  {
    key: 'logistics',
    name: 'Logistics & Shipments',
    description:
      'Product-shipment fulfilment requests with line items, evolved from single-shipment gifting (W3-5) into a country-aware operations workspace: a country-first summary strip, My Queue/Unassigned/Needs Attention views, a distinct destinationCountryCode per shipment (never re-derived from the creator\'s current profile country), a logistics assignee distinct from the requester, and cross-campaign status sync (activity + notifications). Recipient address/phone are redacted server-side for anyone without the LOGISTICS_ADDRESS_VIEW capability (Advanced Roles pass) — never just the legacy VIEWER role.',
    module: 'Logistics',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/campaign-influencers/:id/shipments',
      'POST /api/v1/campaign-influencers/:id/shipments',
      'GET /api/v1/campaigns/:id/shipments',
      'GET /api/v1/shipments',
      'GET /api/v1/shipments/summary',
      'GET /api/v1/shipments/:id',
      'PATCH /api/v1/shipments/:id',
      'POST /api/v1/shipments/:id/status',
      'POST /api/v1/shipments/:id/assign',
    ],
    deepLink: '/logistics',
  },
  {
    key: 'logistics_issues',
    name: 'Logistics Address Clarification',
    description:
      'A lightweight, purpose-built blocker record (never a general-purpose issue tracker) for when a shipment\'s address/phone needs confirming — a fixed type vocabulary (missing/incomplete/unclear address, missing/invalid phone, missing area or city, country mismatch, location clarification, other), routed to the responsible employee (explicit choice, else campaign owner, else the creator\'s relationship owner, else the original requester — never a broadcast). The shipment\'s own ShipmentStatus is never overloaded with a logistics-problem state; addressHealth (Complete/Incomplete/Clarification Requested/Resolved) is derived, never stored. One record surfaces on the Logistics workspace, the Influencer 360 warning banner, the Campaign Operations Board\'s Product-stage blocker, and the canonical Needs Attention feed — never copied. Resolving offers an explicit, opt-in checkbox to also update the creator\'s default shipping address; it never silently rewrites past shipments.',
    module: 'Logistics',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/shipments/:id/issues',
      'POST /api/v1/shipments/:id/issues',
      'POST /api/v1/logistics-issues/:id/resolve',
      'POST /api/v1/logistics-issues/:id/cancel',
    ],
    deepLink: '/logistics',
  },
  {
    key: 'logistics_team_chat',
    name: 'Logistics Team Chat',
    description:
      'An always-accessible, docked channel for logistics-wide coordination ("DHL pickup delayed today") — reuses the SAME Collaboration Layer (Note model, @mentions, replies, pinning, read state) as Campaign Chat and General Team Chat, never a second chat backend. Kept deliberately distinct from per-shipment Comments (also this same primitive, scoped to one shipment). Restricted to actors holding LOGISTICS_MANAGE (people who actually do logistics work), not the broader LOGISTICS_VIEW every Role Profile carries by default for status visibility.',
    module: 'Logistics',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/notes', 'POST /api/v1/notes'],
    deepLink: '/logistics',
  },
  {
    key: 'scripts',
    name: 'Scripts & References',
    description: 'Versioned scripts/briefs with read-only presentation mode.',
    module: 'Scripts',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/scripts/:id',
      'POST /api/v1/scripts',
      'POST /api/v1/scripts/:id/versions',
    ],
    deepLink: '/scripts/:id',
  },
  {
    key: 'content',
    name: 'Published Content & Player',
    description: 'URL parsing, media-independent content data + embed descriptors, monitoring status.',
    module: 'Content',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: 'liveContentEnabled',
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/content/feed',
      'POST /api/v1/content',
      'GET /api/v1/content/:id',
      'PATCH /api/v1/content/:id',
      'GET /api/v1/content/:id/metrics',
    ],
    deepLink: '/content/:id',
  },
  {
    key: 'content_review',
    name: 'Content Command Center (New/Seen/Reviewed/Review Later)',
    description:
      'Per-user content review state (UserContentState) — New/Seen/Reviewed/Review Later never a property of PublishedContent itself. Timeline (day-then-brand grouping), filter chips, daily summary and Review Mode are all built server-side on GET /content/summary and PATCH /content/:id/view-state; internal per-content notes reuse the existing Note model.',
    module: 'Content',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/content/summary',
      'PATCH /api/v1/content/:id/view-state',
      'GET /api/v1/content/:id/notes',
    ],
    deepLink: '/content',
  },
  {
    key: 'whats_new',
    name: "What's New",
    description:
      "Per-user \"since your last visit\" summary (lastWhatsNewViewedAt checkpoint, never lastLoginAt) of real recorded events — new content, campaigns launched, content alerts, overdue deliverables, shipments delivered, submissions approved, usage rights expiring — never a raw activity-log dump.",
    module: 'Content',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/whats-new', 'POST /api/v1/dashboard/whats-new/ack'],
    deepLink: null,
  },
  {
    key: 'calendar',
    name: 'Calendar',
    description: 'Campaign and deliverable calendar (month/week/agenda) driven by the API.',
    module: 'Calendar',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/calendar'],
    deepLink: null,
  },
  {
    key: 'costs',
    name: 'Cost Management',
    description: 'Budgets, agreed costs, gift values, expenses, payment status.',
    module: 'Costs',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/campaigns/:id/costs',
      'POST /api/v1/campaigns/:id/expenses',
      'PATCH /api/v1/expenses/:id',
    ],
    deepLink: null,
  },
  {
    key: 'reports',
    name: 'Reports & Analytics',
    description: 'Campaign/influencer/brand/content/spend reports + CSV export.',
    module: 'Reports',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: 'campaignReportsEnabled',
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/reports'],
    deepLink: null,
  },
  {
    key: 'dashboard',
    name: 'Mission Control',
    description: 'Global + brand aggregated dashboards (pulse, attention, active campaigns).',
    module: 'Dashboard',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/dashboard/global', 'GET /api/v1/dashboard/attention'],
    deepLink: null,
  },
  {
    key: 'notifications',
    name: 'Notifications',
    description: 'In-app notifications with independent delivery channels (push-ready).',
    module: 'Notifications',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/notifications',
      'POST /api/v1/notifications/read',
    ],
    deepLink: null,
  },
  {
    key: 'activity',
    name: 'Activity Feed',
    description: 'Human-readable activity log across brands/campaigns/influencers.',
    module: 'Activity',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/activity'],
    deepLink: null,
  },
  {
    key: 'search',
    name: 'Global Search',
    description: 'Backend-driven search across influencers, campaigns, brands, content.',
    module: 'Search',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/search'],
    deepLink: null,
  },
  {
    key: 'files',
    name: 'Files & Attachments',
    description:
      'Two-phase signed uploads over private object storage (S3/MinIO presigned or local signed proxy) for campaigns, deliverables, scripts, influencers and notes. MIME allowlist + size limits enforced server-side; downloads via short-lived signed URLs.',
    module: 'Files',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'POST /api/v1/files',
      'POST /api/v1/files/complete',
      'GET /api/v1/files',
      'GET /api/v1/files/:id',
      'GET /api/v1/files/:id/blob',
      'DELETE /api/v1/files/:id',
    ],
    deepLink: null,
  },
  {
    key: 'integrations',
    name: 'Integration Capabilities',
    description: 'Public provider capability matrix + admin integration status.',
    module: 'Settings',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/integrations'],
    deepLink: null,
  },
  {
    key: 'client_config',
    name: 'Client Config & Feature Flags',
    description: 'Server-driven remote config, feature flags and mobile app version rules.',
    module: 'Settings',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/client-config', 'GET /api/v1/platform/features'],
    deepLink: null,
  },
  {
    key: 'storage_admin',
    name: 'Storage Administration',
    description: 'Admin view of object-storage configuration and usage: driver, private-by-default access model, upload limits, allowed types, object count and total size.',
    module: 'Settings',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ADMIN_ONLY,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/platform/storage'],
    deepLink: null,
  },
  {
    key: 'audit_admin',
    name: 'Audit Log',
    description: 'Admin-only, workspace-wide audit trail with server-side filters (actor, action, entity, brand/campaign, date range, free-text) and cursor pagination. Authorization enforced at the API layer (requireAdmin), not the UI.',
    module: 'Settings',
    classification: 'ADMIN_DESKTOP_ONLY',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: false,
    permissions: ADMIN_ONLY,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/platform/audit'],
    deepLink: null,
  },
  {
    key: 'provider_secrets',
    name: 'Provider Secrets',
    description: 'Server-only social provider credentials. Never exposed to any client.',
    module: 'Settings',
    classification: 'ADMIN_DESKTOP_ONLY',
    apiStatus: 'ADMIN_SERVER_ONLY',
    webStatus: 'READY',
    mobileReady: false,
    permissions: ADMIN_ONLY,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['PATCH /api/v1/integrations/:platform'],
    deepLink: null,
  },
  {
    key: 'user_admin',
    name: 'User Administration',
    description:
      'Create/manage internal staff and admin users: lifecycle (activate/deactivate, reset password, remove), brand scope, country scope, and — since the Advanced Roles pass — Role Profile assignment and per-user capability overrides, with a live "this user can/cannot" Permission Preview computed from the exact same resolution logic that gates real access (never a second, drifting approximation).',
    module: 'Settings',
    classification: 'ADMIN_DESKTOP_ONLY',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: false,
    permissions: ADMIN_ONLY,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/users',
      'POST /api/v1/users',
      'PATCH /api/v1/users/:id',
      'DELETE /api/v1/users/:id',
      'POST /api/v1/users/:id/reset-password',
      'GET /api/v1/users/:id/brand-access',
      'PUT /api/v1/users/:id/brand-access',
      'GET /api/v1/users/:id/country-access',
      'PUT /api/v1/users/:id/country-access',
      'GET /api/v1/users/:id/permissions',
      'POST /api/v1/users/:id/permissions/preview',
      'PUT /api/v1/users/:id/capabilities',
    ],
    deepLink: '/settings/users',
  },
  {
    key: 'monitoring',
    name: 'Content Monitoring',
    description: 'Background availability monitoring, status changes, alerts.',
    module: 'Content',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/content/:id/monitoring'],
    deepLink: null,
  },
  {
    key: 'creator_360',
    name: 'Creator 360',
    description: 'Relationship snapshot (owner, brands worked with, rate range, outstanding payment, delivery reliability) and a cross-source master timeline (campaign/content/UGC/logistics/payment/notes/activity) on the influencer profile.',
    module: 'Influencers',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/influencers/:id/snapshot', 'GET /api/v1/influencers/:id/reliability', 'GET /api/v1/influencers/:id/timeline'],
    deepLink: '/influencers/:id',
  },
  {
    key: 'campaign_operations_board',
    name: 'Campaign Operations Board',
    description: 'Per-influencer 8-stage pipeline (Agreement/Product/Content Due/Draft/Review/Approved/Published/Payment) derived read-time from roster/deliverable/submission/shipment records, with clickable status filter chips.',
    module: 'Campaigns',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/campaigns/:id/operations-board'],
    deepLink: '/campaigns/:id',
  },
  {
    key: 'data_quality',
    name: 'Data Quality',
    description: 'Missing/incomplete-data findings (real counts, never a fabricated score) and possible-duplicate creator detection (confidence-graded by matched hard identifiers vs. name-only), both derived read-time and optionally brand-scoped.',
    module: 'Data Quality',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/data-quality/report', 'GET /api/v1/data-quality/duplicates'],
    deepLink: '/data-quality',
  },
  {
    key: 'workflow_integrity_guard',
    name: 'Workflow Integrity Guard',
    description: 'Read-only relational-consistency sweep across content/deliverables/campaigns/usage rights — surfaces mismatches the content-association and submission-review write paths are supposed to prevent, without ever repairing them.',
    module: 'Data Quality',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/integrity/findings'],
    deepLink: '/data-quality',
  },
  {
    key: 'bulk_influencer_actions',
    name: 'Bulk Creator Actions',
    description: 'Multi-select assign-owner / add-tag / set-relationship-status across the influencer directory. Preview (the exact per-row outcome) is available to any staff member; applying the change is admin-only.',
    module: 'Influencers',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['POST /api/v1/influencers/bulk/preview', 'POST /api/v1/influencers/bulk/execute'],
    deepLink: '/influencers',
  },
  {
    key: 'advanced_roles',
    name: 'Advanced Roles & Capabilities',
    description:
      'Replaces the flat ADMIN/STAFF/VIEWER model\'s all-or-nothing authorization with an optional, additive Role Profile (System Admin, General Manager, Operations Manager, Logistics, Influencer Manager, Viewer) that resolves to a default set of ~22 named capabilities, refined per user by explicit grant/revoke overrides — never scattered `actor.role === X` checks; every authorization decision funnels through one centralized resolveCapabilitiesFor()/hasCapability(). A role/profile change revokes the user\'s live sessions and takes effect on their very next request, not after their token expires. A user with no Role Profile assigned keeps their exact pre-existing legacy STAFF/VIEWER behavior — zero behavior change for anyone not explicitly migrated.',
    module: 'Settings',
    classification: 'ADMIN_DESKTOP_ONLY',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: false,
    permissions: ADMIN_ONLY,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/users/:id/permissions', 'POST /api/v1/users/:id/permissions/preview', 'PUT /api/v1/users/:id/capabilities', 'PATCH /api/v1/users/:id'],
    deepLink: '/settings/users',
  },
  {
    key: 'country_scoping',
    name: 'Country Scoping',
    description:
      'ISO-style country-code access control, independent of (and composable with) brand scope — both must be satisfied where both apply. Applied server-side everywhere a country-relevant record is read: the Logistics workspace (by a shipment\'s own destinationCountryCode, a point-in-time snapshot that is never re-derived from the creator\'s current profile country after the fact) and the Influencer directory (by the creator\'s own countryCode). Enforced on both list endpoints (an out-of-scope filter matches nothing) and direct-by-id endpoints (a country-scoped actor gets a 404, not just a hidden row, when guessing an out-of-scope id) — verified for both shipments and influencers. An actor with zero explicit country-access rows (including ADMIN) is unrestricted, so this is fully additive.',
    module: 'Logistics',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/users/:id/country-access',
      'PUT /api/v1/users/:id/country-access',
      'GET /api/v1/shipments',
      'GET /api/v1/influencers',
    ],
    deepLink: '/logistics',
  },
];

export const FEATURE_MODULES = Array.from(new Set(FEATURES.map((f) => f.module)));

export function getFeature(key: string): FeatureEntry | undefined {
  return FEATURES.find((f) => f.key === key);
}

export function computeCoverage() {
  const total = FEATURES.length;
  const apiReady = FEATURES.filter((f) => f.apiStatus === 'READY').length;
  const webReady = FEATURES.filter((f) => f.webStatus === 'READY').length;
  const mobileReady = FEATURES.filter((f) => f.mobileReady).length;
  const adminOnly = FEATURES.filter((f) => f.classification === 'ADMIN_DESKTOP_ONLY').length;
  const shared = FEATURES.filter((f) => f.classification === 'SHARED');
  const mobileReadinessPercent = shared.length
    ? Math.round((shared.filter((f) => f.mobileReady).length / shared.length) * 100)
    : 0;
  return { total, apiReady, webReady, mobileReady, adminOnly, mobileReadinessPercent };
}

export function listApiEndpoints(): { method: string; path: string; module: string }[] {
  const out: { method: string; path: string; module: string }[] = [];
  for (const f of FEATURES) {
    for (const ep of f.apiEndpoints) {
      const [method, path] = ep.split(' ');
      out.push({ method: method ?? 'GET', path: path ?? ep, module: f.module });
    }
  }
  return out;
}
