import type { FeatureClass, FeatureStatus } from '../dto';
import type { UserRole } from '../enums';

/**
 * Feature Registry (addendum §12, §36, §37) — the single code-level source of
 * truth for what the platform can do. The Platform & API admin views, the
 * Mobile Readiness dashboard, GET /api/v1/platform/* and the generated
 * docs/FEATURE_MATRIX.md all derive from THIS list, so nothing goes stale.
 *
 * "Mobile Ready" is not a database fact — a feature is mobile-ready only when
 * its business logic is server-side, an API endpoint exists and is documented,
 * auth + permissions are enforced server-side, contracts are stable, media is
 * represented independently of the Web UI, and filtering/pagination are
 * server-side (§37). We set `mobileReady` accordingly, honestly.
 */

export interface FeatureEntry {
  key: string;
  name: string;
  description: string;
  module: string;
  classification: FeatureClass;
  apiStatus: FeatureStatus;
  webStatus: FeatureStatus;
  mobileReady: boolean;
  permissions: UserRole[];
  flag: string | null;
  minApiVersion: string;
  apiEndpoints: string[];
  deepLink: string | null;
}

const ALL: UserRole[] = ['ADMIN', 'STAFF'];
const ADMIN_ONLY: UserRole[] = ['ADMIN'];

export const FEATURES: FeatureEntry[] = [
  {
    key: 'auth',
    name: 'Authentication',
    description: 'Login, token refresh, current user, logout, device sessions.',
    module: 'Auth',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'POST /api/v1/auth/login',
      'POST /api/v1/auth/refresh',
      'POST /api/v1/auth/logout',
      'POST /api/v1/auth/change-password',
      'GET /api/v1/auth/me',
      'PATCH /api/v1/auth/me/preferences',
      'GET /api/v1/auth/sessions',
    ],
    deepLink: null,
  },
  {
    key: 'brands',
    name: 'Brands & Brand Switching',
    description: 'Multi-brand workspaces, brand CRUD and brand-scoped views.',
    module: 'Brands',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/brands',
      'POST /api/v1/brands',
      'GET /api/v1/brands/:id',
      'PATCH /api/v1/brands/:id',
      'GET /api/v1/brands/:id/dashboard',
    ],
    deepLink: '/brands/:slug',
  },
  {
    key: 'influencers',
    name: 'Influencer Management',
    description:
      'Directory, add-from-URL, 360 profile, social accounts, notes, tags, brand relationships.',
    module: 'Influencers',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/influencers',
      'GET /api/v1/influencers/export',
      'POST /api/v1/influencers',
      'GET /api/v1/influencers/:id',
      'PATCH /api/v1/influencers/:id',
      'POST /api/v1/influencers/resolve',
      'GET /api/v1/influencers/:id/followers',
      'GET /api/v1/influencers/:id/audience-health',
    ],
    deepLink: '/influencers/:id',
  },
  {
    key: 'social_accounts',
    name: 'Social Accounts & Metrics',
    description: 'Per-network accounts, follower history snapshots, provenance.',
    module: 'Metrics',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'POST /api/v1/influencers/:id/social-accounts',
      'PATCH /api/v1/social-accounts/:id',
      'POST /api/v1/social-accounts/:id/sync',
    ],
    deepLink: null,
  },
  {
    key: 'campaigns',
    name: 'Campaign Management',
    description: 'Campaign CRUD, workspace, progress, influencers, statuses.',
    module: 'Campaigns',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/campaigns',
      'POST /api/v1/campaigns',
      'GET /api/v1/campaigns/:id',
      'PATCH /api/v1/campaigns/:id',
      'POST /api/v1/campaigns/:id/influencers',
    ],
    deepLink: '/campaigns/:id',
  },
  {
    key: 'deliverables',
    name: 'Deliverables',
    description: 'Per-influencer deliverables, statuses, requirements, publish links.',
    module: 'Deliverables',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'POST /api/v1/campaign-influencers/:id/deliverables',
      'PATCH /api/v1/deliverables/:id',
    ],
    deepLink: null,
  },
  {
    key: 'submissions',
    name: 'Deliverable Submissions & Review',
    description:
      'UGC/draft submission, threaded review (approve / request changes / reject); UGC deliverables complete without any public URL.',
    module: 'Deliverables',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/deliverables/:id/submissions',
      'POST /api/v1/deliverables/:id/submissions',
      'GET /api/v1/submissions/:id',
      'POST /api/v1/submissions/:id/review',
      'POST /api/v1/submissions/:id/comments',
      'GET /api/v1/campaigns/:id/submissions',
    ],
    deepLink: null,
  },
  {
    key: 'logistics',
    name: 'Logistics & Shipments',
    description:
      "Product-shipment fulfilment requests with line items, evolved from single-shipment gifting (W3-5) into a country-aware operations workspace: a country-first summary strip, My Queue/Unassigned/Needs Attention views, a distinct destinationCountryCode per shipment (never re-derived from the creator's current profile country), a logistics assignee distinct from the requester, and cross-campaign status sync (activity + notifications). Recipient address/phone are redacted server-side for anyone without the LOGISTICS_ADDRESS_VIEW capability (Advanced Roles pass) — never just the legacy VIEWER role.",
    module: 'Logistics',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/campaign-influencers/:id/shipments',
      'POST /api/v1/campaign-influencers/:id/shipments',
      'GET /api/v1/campaigns/:id/shipments',
      'GET /api/v1/shipments',
      'GET /api/v1/shipments/summary',
      'GET /api/v1/shipments/:id',
      'PATCH /api/v1/shipments/:id',
      'POST /api/v1/shipments/:id/status',
      'POST /api/v1/shipments/:id/assign',
    ],
    deepLink: '/logistics',
  },
  {
    key: 'logistics_issues',
    name: 'Logistics Address Clarification',
    description:
      "A lightweight, purpose-built blocker record (never a general-purpose issue tracker) for when a shipment's address/phone needs confirming — a fixed type vocabulary (missing/incomplete/unclear address, missing/invalid phone, missing area or city, country mismatch, location clarification, other), routed to the responsible employee (explicit choice, else campaign owner, else the creator's relationship owner, else the original requester — never a broadcast). The shipment's own ShipmentStatus is never overloaded with a logistics-problem state; addressHealth (Complete/Incomplete/Clarification Requested/Resolved) is derived, never stored. One record surfaces on the Logistics workspace, the Influencer 360 warning banner, the Campaign Operations Board's Product-stage blocker, and the canonical Needs Attention feed — never copied. Resolving offers an explicit, opt-in checkbox to also update the creator's default shipping address; it never silently rewrites past shipments.",
    module: 'Logistics',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/shipments/:id/issues',
      'POST /api/v1/shipments/:id/issues',
      'POST /api/v1/logistics-issues/:id/resolve',
      'POST /api/v1/logistics-issues/:id/cancel',
    ],
    deepLink: '/logistics',
  },
  {
    key: 'logistics_team_chat',
    name: 'Logistics Team Chat',
    description:
      'An always-accessible, docked channel for logistics-wide coordination ("DHL pickup delayed today") — reuses the SAME Collaboration Layer (Note model, @mentions, replies, pinning, read state) as Campaign Chat and General Team Chat, never a second chat backend. Kept deliberately distinct from per-shipment Comments (also this same primitive, scoped to one shipment). Restricted to actors holding LOGISTICS_MANAGE (people who actually do logistics work), not the broader LOGISTICS_VIEW every Role Profile carries by default for status visibility.',
    module: 'Logistics',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/notes', 'POST /api/v1/notes'],
    deepLink: '/logistics',
  },
  {
    key: 'scripts',
    name: 'Scripts & References',
    description: 'Versioned scripts/briefs with read-only presentation mode.',
    module: 'Scripts',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/scripts/:id',
      'POST /api/v1/scripts',
      'POST /api/v1/scripts/:id/versions',
    ],
    deepLink: '/scripts/:id',
  },
  {
    key: 'content',
    name: 'Published Content & Player',
    description:
      'URL parsing, media-independent content data + embed descriptors, monitoring status.',
    module: 'Content',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: 'liveContentEnabled',
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/content/feed',
      'POST /api/v1/content',
      'POST /api/v1/content/lookup',
      'POST /api/v1/campaigns/:id/content/link-roster',
      'GET /api/v1/content/:id',
      'PATCH /api/v1/content/:id',
      'GET /api/v1/content/:id/metrics',
    ],
    deepLink: '/content/:id',
  },
  {
    key: 'content_review',
    name: 'Content Command Center (New/Seen/Reviewed/Review Later)',
    description:
      'Per-user content review state (UserContentState) — New/Seen/Reviewed/Review Later never a property of PublishedContent itself. Timeline (day-then-brand grouping), filter chips, daily summary and Review Mode are all built server-side on GET /content/summary and PATCH /content/:id/view-state; internal per-content notes reuse the existing Note model.',
    module: 'Content',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/content/summary',
      'PATCH /api/v1/content/:id/view-state',
      'GET /api/v1/content/:id/notes',
    ],
    deepLink: '/content',
  },
  {
    key: 'whats_new',
    name: "What's New",
    description:
      'Per-user "since your last visit" summary (lastWhatsNewViewedAt checkpoint, never lastLoginAt) of real recorded events — new content, campaigns launched, content alerts, overdue deliverables, shipments delivered, submissions approved, usage rights expiring — never a raw activity-log dump.',
    module: 'Content',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/whats-new', 'POST /api/v1/dashboard/whats-new/ack'],
    deepLink: null,
  },
  {
    key: 'calendar',
    name: 'Calendar',
    description: 'Campaign and deliverable calendar (month/week/agenda) driven by the API.',
    module: 'Calendar',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/calendar'],
    deepLink: null,
  },
  {
    key: 'costs',
    name: 'Cost Management',
    description: 'Budgets, agreed costs, gift values, expenses, payment status.',
    module: 'Costs',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/campaigns/:id/costs',
      'POST /api/v1/campaigns/:id/expenses',
      'PATCH /api/v1/expenses/:id',
    ],
    deepLink: null,
  },
  {
    key: 'reports',
    name: 'Reports & Analytics',
    description: 'Campaign/influencer/brand/content/spend reports + CSV export.',
    module: 'Reports',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: 'campaignReportsEnabled',
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/reports'],
    deepLink: null,
  },
  {
    key: 'dashboard',
    name: 'Mission Control',
    description: 'Global + brand aggregated dashboards (pulse, attention, active campaigns).',
    module: 'Dashboard',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/dashboard/global', 'GET /api/v1/dashboard/attention'],
    deepLink: null,
  },
  {
    key: 'notifications',
    name: 'Notifications',
    description: 'In-app notifications with independent delivery channels (push-ready).',
    module: 'Notifications',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/notifications', 'POST /api/v1/notifications/read'],
    deepLink: null,
  },
  {
    key: 'activity',
    name: 'Activity Feed',
    description: 'Human-readable activity log across brands/campaigns/influencers.',
    module: 'Activity',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/activity'],
    deepLink: null,
  },
  {
    key: 'search',
    name: 'Global Search',
    description:
      'Backend-driven search across influencers, campaigns, brands, content: the quick palette, and a full ranked page (notes, tags, captions; counts per type; paginated).',
    module: 'Search',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/search', 'GET /api/v1/search/page'],
    deepLink: '/search',
  },
  {
    key: 'files',
    name: 'Files & Attachments',
    description:
      'Two-phase signed uploads over private object storage (S3/MinIO presigned or local signed proxy) for campaigns, deliverables, scripts, influencers and notes. MIME allowlist + size limits enforced server-side; downloads via short-lived signed URLs.',
    module: 'Files',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'POST /api/v1/files',
      'POST /api/v1/files/complete',
      'GET /api/v1/files',
      'GET /api/v1/files/:id',
      'GET /api/v1/files/:id/blob',
      'DELETE /api/v1/files/:id',
    ],
    deepLink: null,
  },
  {
    key: 'integrations',
    name: 'Integration Capabilities',
    description: 'Public provider capability matrix + admin integration status.',
    module: 'Settings',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/integrations'],
    deepLink: null,
  },
  {
    key: 'client_config',
    name: 'Client Config & Feature Flags',
    description: 'Server-driven remote config, feature flags and mobile app version rules.',
    module: 'Settings',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/client-config', 'GET /api/v1/platform/features'],
    deepLink: null,
  },
  {
    key: 'storage_admin',
    name: 'Storage Administration',
    description:
      'Admin view of object-storage configuration and usage: driver, private-by-default access model, upload limits, allowed types, object count and total size.',
    module: 'Settings',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ADMIN_ONLY,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/platform/storage'],
    deepLink: null,
  },
  {
    key: 'audit_admin',
    name: 'Audit Log',
    description:
      'Admin-only, workspace-wide audit trail with server-side filters (actor, action, entity, brand/campaign, date range, free-text) and cursor pagination. Authorization enforced at the API layer (requireAdmin), not the UI.',
    module: 'Settings',
    classification: 'ADMIN_DESKTOP_ONLY',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: false,
    permissions: ADMIN_ONLY,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/platform/audit'],
    deepLink: null,
  },
  {
    key: 'provider_secrets',
    name: 'Provider Secrets',
    description: 'Server-only social provider credentials. Never exposed to any client.',
    module: 'Settings',
    classification: 'ADMIN_DESKTOP_ONLY',
    apiStatus: 'ADMIN_SERVER_ONLY',
    webStatus: 'READY',
    mobileReady: false,
    permissions: ADMIN_ONLY,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['PATCH /api/v1/integrations/:platform'],
    deepLink: null,
  },
  {
    key: 'user_admin',
    name: 'User Administration',
    description:
      'Create/manage internal staff and admin users: lifecycle (activate/deactivate, reset password, remove), brand scope, country scope, and — since the Advanced Roles pass — Role Profile assignment and per-user capability overrides, with a live "this user can/cannot" Permission Preview computed from the exact same resolution logic that gates real access (never a second, drifting approximation).',
    module: 'Settings',
    classification: 'ADMIN_DESKTOP_ONLY',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: false,
    permissions: ADMIN_ONLY,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/users',
      'POST /api/v1/users',
      'PATCH /api/v1/users/:id',
      'DELETE /api/v1/users/:id',
      'POST /api/v1/users/:id/reset-password',
      'GET /api/v1/users/:id/brand-access',
      'PUT /api/v1/users/:id/brand-access',
      'GET /api/v1/users/:id/country-access',
      'PUT /api/v1/users/:id/country-access',
      'GET /api/v1/users/:id/permissions',
      'POST /api/v1/users/:id/permissions/preview',
      'PUT /api/v1/users/:id/capabilities',
    ],
    deepLink: '/settings/users',
  },
  {
    key: 'monitoring',
    name: 'Content Monitoring',
    description: 'Background availability monitoring, status changes, alerts.',
    module: 'Content',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/content/:id/monitoring'],
    deepLink: null,
  },
  {
    key: 'creator_360',
    name: 'Creator 360',
    description:
      'Relationship snapshot (owner, brands worked with, rate range, outstanding payment, delivery reliability) and a cross-source master timeline (campaign/content/UGC/logistics/payment/notes/activity) on the influencer profile.',
    module: 'Influencers',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/influencers/:id/snapshot',
      'GET /api/v1/influencers/:id/reliability',
      'GET /api/v1/influencers/:id/timeline',
    ],
    deepLink: '/influencers/:id',
  },
  {
    key: 'campaign_operations_board',
    name: 'Campaign Operations Board',
    description:
      'Per-influencer 8-stage pipeline (Agreement/Product/Content Due/Draft/Review/Approved/Published/Payment) derived read-time from roster/deliverable/submission/shipment records, with clickable status filter chips.',
    module: 'Campaigns',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/campaigns/:id/operations-board'],
    deepLink: '/campaigns/:id',
  },
  {
    key: 'data_quality',
    name: 'Data Quality',
    description:
      'Missing/incomplete-data findings (real counts, never a fabricated score) and possible-duplicate creator detection (confidence-graded by matched hard identifiers vs. name-only), both derived read-time and optionally brand-scoped.',
    module: 'Data Quality',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/data-quality/report', 'GET /api/v1/data-quality/duplicates'],
    deepLink: '/data-quality',
  },
  {
    key: 'workflow_integrity_guard',
    name: 'Workflow Integrity Guard',
    description:
      'Read-only relational-consistency sweep across content/deliverables/campaigns/usage rights — surfaces mismatches the content-association and submission-review write paths are supposed to prevent, without ever repairing them.',
    module: 'Data Quality',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/integrity/findings'],
    deepLink: '/data-quality',
  },
  {
    key: 'bulk_influencer_actions',
    name: 'Bulk Creator Actions',
    description:
      'Multi-select assign-owner / add-tag / set-relationship-status across the influencer directory. Preview (the exact per-row outcome) is available to any staff member; applying the change is admin-only.',
    module: 'Influencers',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'POST /api/v1/influencers/bulk/preview',
      'POST /api/v1/influencers/bulk/execute',
    ],
    deepLink: '/influencers',
  },
  {
    key: 'advanced_roles',
    name: 'Advanced Roles & Capabilities',
    description:
      "Replaces the flat ADMIN/STAFF/VIEWER model's all-or-nothing authorization with an optional, additive Role Profile (System Admin, General Manager, Operations Manager, Logistics, Influencer Manager, Viewer) that resolves to a default set of ~22 named capabilities, refined per user by explicit grant/revoke overrides — never scattered `actor.role === X` checks; every authorization decision funnels through one centralized resolveCapabilitiesFor()/hasCapability(). A role/profile change revokes the user's live sessions and takes effect on their very next request, not after their token expires. A user with no Role Profile assigned keeps their exact pre-existing legacy STAFF/VIEWER behavior — zero behavior change for anyone not explicitly migrated.",
    module: 'Settings',
    classification: 'ADMIN_DESKTOP_ONLY',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: false,
    permissions: ADMIN_ONLY,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/users/:id/permissions',
      'POST /api/v1/users/:id/permissions/preview',
      'PUT /api/v1/users/:id/capabilities',
      'PATCH /api/v1/users/:id',
    ],
    deepLink: '/settings/users',
  },
  {
    key: 'country_scoping',
    name: 'Country Scoping',
    description:
      "ISO-style country-code access control, independent of (and composable with) brand scope — both must be satisfied where both apply. Applied server-side everywhere a country-relevant record is read: the Logistics workspace (by a shipment's own destinationCountryCode, a point-in-time snapshot that is never re-derived from the creator's current profile country after the fact) and the Influencer directory (by the creator's own countryCode). Enforced on both list endpoints (an out-of-scope filter matches nothing) and direct-by-id endpoints (a country-scoped actor gets a 404, not just a hidden row, when guessing an out-of-scope id) — verified for both shipments and influencers. An actor with zero explicit country-access rows (including ADMIN) is unrestricted, so this is fully additive.",
    module: 'Logistics',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/users/:id/country-access',
      'PUT /api/v1/users/:id/country-access',
      'GET /api/v1/shipments',
      'GET /api/v1/influencers',
    ],
    deepLink: '/logistics',
  },
  {
    key: 'sales_roi',
    name: 'Sales & ROI',
    description:
      "Promo codes and tracking links per creator per campaign, and the brand's own sales credited to them: a shop order file (CSV or pasted from Excel — Arabic digits, Gulf currencies, day-first dates) matched by code or link, checked first without saving, never counting an order twice, cancelled orders left out, and undoable as a whole; or totals entered by hand. A reused code goes to the campaign whose dates cover the order. Short links (/r/<slug>) count people's clicks per Kuwait day (not link previews) and add UTM tags. Shows orders, revenue per currency, clicks and conversion; return on spend and cost per order only with finance access. Nothing is estimated.",
    module: 'Campaigns',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/campaigns/:id/sales',
      'POST /api/v1/campaigns/:id/promo-codes',
      'PATCH /api/v1/promo-codes/:id',
      'DELETE /api/v1/promo-codes/:id',
      'POST /api/v1/campaigns/:id/tracking-links',
      'PATCH /api/v1/tracking-links/:id',
      'DELETE /api/v1/tracking-links/:id',
      'POST /api/v1/campaigns/:id/sales',
      'DELETE /api/v1/sales/:id',
      'POST /api/v1/brands/:id/sales/import',
      'DELETE /api/v1/sales-imports/:id',
      'GET /api/v1/public/links/:slug',
    ],
    deepLink: '/campaigns',
  },
  {
    key: 'client_report_links',
    name: 'Client report links',
    description:
      "Share a campaign's client report with the brand's team by link, no account needed (/share/r/<token>). The link fixes the report's language and whether costs show (off unless someone who can see costs turns it on), can expire (30 days by default) and be turned off, and counts how often people opened it (link previews aren't counted). The page always shows the latest numbers and prints to PDF or downloads as Excel. Making and turning off links needs CAMPAIGNS_MANAGE; brand scope applies.",
    module: 'Campaigns',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/campaigns/:id/report-shares',
      'POST /api/v1/campaigns/:id/report-shares',
      'POST /api/v1/report-shares/:id/revoke',
      'GET /api/v1/public/reports/:token',
      'GET /api/v1/public/reports/:token/xlsx',
    ],
    deepLink: '/campaigns',
  },
  {
    key: 'creator_task_links',
    name: 'Creator task links',
    description:
      "A creator's part of one campaign on a no-login link (/share/c/<token>), made from their roster row and sent on WhatsApp with the brief: the brief, their deliverables with due dates and requirements, the brand-approved script, their drafts with the team's decision and note, and where they send a new draft (a link to the file) or the live post link. Drafts land in the normal review queue marked as sent by the creator; a post link waits on the deliverable for the team to check and add. Fees, internal notes, team comments and other creators' work are never shown. The link fixes the page language (the creator can switch), can expire (90 days by default) and be turned off, and stops working if the creator leaves the campaign. Making links needs CAMPAIGNS_MANAGE or INFLUENCERS_MANAGE; brand and country scope apply.",
    module: 'Campaigns',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/campaign-influencers/:id/creator-links',
      'POST /api/v1/campaign-influencers/:id/creator-links',
      'POST /api/v1/creator-links/:id/revoke',
      'GET /api/v1/public/creator/:token',
      'POST /api/v1/public/creator/:token/deliverables/:deliverableId/drafts',
      'POST /api/v1/public/creator/:token/deliverables/:deliverableId/posted',
    ],
    deepLink: '/campaigns',
  },
  {
    key: 'post_discovery',
    name: 'Post discovery',
    description:
      "While a campaign runs, the worker reads the roster creators' newest posts on Instagram (Professional accounts, Business Discovery), YouTube (uploads) and X (user timeline, on a tier that allows it) — each account at most every 6 hours — and suggests the posts whose caption carries the creator's promo code, the deliverables' hashtags or mentions, the brand's name, or (with a single running campaign) an ad disclosure, together with the likely deliverable. Nothing is tracked until someone adds it; dismissed and already-tracked posts are never suggested again. The team is notified when posts are found and can look now from the campaign's content view.",
    module: 'Content',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/campaigns/:id/discovered-posts',
      'POST /api/v1/campaigns/:id/discover-posts',
      'POST /api/v1/discovered-posts/:id/add',
      'POST /api/v1/discovered-posts/:id/dismiss',
    ],
    deepLink: '/campaigns',
  },
  {
    key: 'creator_licences',
    name: 'Creator advertising licences',
    description:
      "Each creator's advertising licence per country (issuer, number, dates, scanned licence from their files). A campaign names the countries it is for; for the countries an admin marks as needing a licence (Settings → Compliance; Kuwait, Saudi Arabia and the UAE by default), every creator still on the roster is checked: no licence, expired, or ending before the campaign does. The roster shows it per creator, Needs Attention raises one line per campaign whose confirmed creators aren't covered, and the worker warns 30 days before a licence expires (again after a renewal).",
    module: 'Influencers',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/influencers/:id/licences',
      'POST /api/v1/influencers/:id/licences',
      'PATCH /api/v1/licences/:id',
      'DELETE /api/v1/licences/:id',
      'GET /api/v1/campaigns/:id/licences',
      'GET /api/v1/compliance/settings',
      'PUT /api/v1/compliance/settings',
    ],
    deepLink: '/settings/compliance',
  },
  {
    key: 'audience_insights',
    name: 'Audience insights and creator selection filters',
    description:
      "Who follows each of a creator's accounts — top countries, women/men, age groups, engagement — typed from the creator's insights screenshot (kept with their files), newest first per account. The directory filters on the newest breakdown (\"audience in Kuwait ≥ 40%\"), on engagement rate, language, gender and the creator's usual fee per post.",
    module: 'Influencers',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'GET /api/v1/influencers/:id/audience',
      'POST /api/v1/social-accounts/:id/audience',
      'PATCH /api/v1/audience/:id',
      'DELETE /api/v1/audience/:id',
      'GET /api/v1/influencers',
    ],
    deepLink: '/influencers',
  },
  {
    key: 'creator_suggestions',
    name: 'Suggested creators',
    description:
      "On a campaign's sourcing list: creators not on it yet, ranked by plain rules — audience in the campaign's countries, based there, worked with the brand before, engagement, and the campaign's platforms — each with the reasons. One click adds them as a candidate with the match as their fit score.",
    module: 'Campaigns',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/campaigns/:id/candidates/suggestions', 'POST /api/v1/campaigns/:id/candidates'],
    deepLink: '/campaigns',
  },
  {
    key: 'rate_benchmarks',
    name: 'Rate benchmarks',
    description:
      "What creators like these were paid in the agency's own confirmed paid bookings — the median fee per post, cost per view and engagement rate with the middle half of bookings — by the platform and follower size (nano to mega) the creator had when booked. Shown beside the fee when booking a creator, and as a platform × size grid; one currency at a time, at least three bookings per figure, fee figures only with finance access.",
    module: 'Reports',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/reports/benchmarks'],
    deepLink: '/reports/benchmarks',
  },
  {
    key: 'ai_settings',
    name: 'AI assistance settings',
    description:
      "Settings → AI: off by default. An admin turns AI assistance on with a Claude API key (stored encrypted, only its last four characters shown) and a model ID, chooses which AI features are allowed, and sets one monthly request limit shared by all of them (Kuwait calendar month). Every request is logged — who, what for, tokens — never the image or text.",
    module: 'Settings',
    classification: 'ADMIN_DESKTOP_ONLY',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: false,
    permissions: ADMIN_ONLY,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/platform/ai', 'PATCH /api/v1/platform/ai'],
    deepLink: '/settings/ai',
  },
  {
    key: 'ai_screenshot_metrics',
    name: 'Read metrics from an insights screenshot (AI)',
    description:
      "In \"Enter metrics\": Claude reads the numbers (views, likes, comments, shares, saves and the date, when shown) from a screenshot attached to the post and fills the form in, marked for checking — nothing is saved until a person saves. Numbers the screenshot doesn't show stay empty; an image that isn't an insights screen fills nothing. Only when an admin has turned it on.",
    module: 'Content',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/ai/status', 'POST /api/v1/content/:id/metrics/read-screenshot'],
    deepLink: '/content',
  },
  {
    key: 'ai_writing_help',
    name: 'AI writing help',
    description:
      "Suggestions from Claude for the team to edit — nothing is saved until they save: a first draft of a script version from the campaign brief (and the deliverable's requirements and the script's current text), in Arabic or English, always keeping the required hashtags and mentions; suggested review notes on a creator's draft from the brief, the approved script and the caption check (the reviewer decides); and a short summary for the client report from the figures the reader may see (no costs without finance access). Only when an admin has turned writing help on.",
    module: 'Campaigns',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: [
      'POST /api/v1/campaigns/:id/scripts/ai-draft',
      'POST /api/v1/submissions/:id/ai-review',
      'POST /api/v1/campaigns/:id/report/ai-summary',
    ],
    deepLink: '/campaigns',
  },
  {
    key: 'caption_check',
    name: 'Caption check',
    description:
      "Checks a caption against what its deliverable asks for: the deliverable's and the brand-approved script's hashtags and mentions, and — for paid or gifted work the creator posts (not FREE deals, not UGC) — an ad disclosure (#إعلان, #اعلان, #ad, #sponsored, \"paid partnership\"…). The creator sees it live while writing the caption on their task link, the team sees it when reviewing a draft and on the post's page, and Needs Attention raises one line per running campaign with live posts that don't say they're ads.",
    module: 'Content',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/deliverables/:id/caption-rules'],
    deepLink: '/campaigns',
  },
  {
    key: 'my_work',
    name: 'My work and approvals',
    description:
      "My work lists what's waiting on the signed-in person — drafts to review, deliverables overdue or due in the next 3 days, and posts found on creators' accounts, for the campaigns and creators they own, plus shipments and address issues assigned to them. Approvals lists every draft waiting for review across campaigns (or only the person's own), reviewed in place. The sidebar shows both counts.",
    module: 'Dashboard',
    classification: 'SHARED',
    apiStatus: 'READY',
    webStatus: 'READY',
    mobileReady: true,
    permissions: ALL,
    flag: null,
    minApiVersion: 'v1',
    apiEndpoints: ['GET /api/v1/me/work', 'GET /api/v1/me/work/counts', 'GET /api/v1/approvals'],
    deepLink: '/my-work',
  },
];

export const FEATURE_MODULES = Array.from(new Set(FEATURES.map((f) => f.module)));

export function getFeature(key: string): FeatureEntry | undefined {
  return FEATURES.find((f) => f.key === key);
}

export function computeCoverage() {
  const total = FEATURES.length;
  const apiReady = FEATURES.filter((f) => f.apiStatus === 'READY').length;
  const webReady = FEATURES.filter((f) => f.webStatus === 'READY').length;
  const mobileReady = FEATURES.filter((f) => f.mobileReady).length;
  const adminOnly = FEATURES.filter((f) => f.classification === 'ADMIN_DESKTOP_ONLY').length;
  const shared = FEATURES.filter((f) => f.classification === 'SHARED');
  const mobileReadinessPercent = shared.length
    ? Math.round((shared.filter((f) => f.mobileReady).length / shared.length) * 100)
    : 0;
  return { total, apiReady, webReady, mobileReady, adminOnly, mobileReadinessPercent };
}

export function listApiEndpoints(): { method: string; path: string; module: string }[] {
  const out: { method: string; path: string; module: string }[] = [];
  for (const f of FEATURES) {
    for (const ep of f.apiEndpoints) {
      const [method, path] = ep.split(' ');
      out.push({ method: method ?? 'GET', path: path ?? ep, module: f.module });
    }
  }
  return out;
}
