/* eslint-disable no-console */
/**
 * Generates docs from the code-level source of truth so they never go stale:
 *   docs/FEATURE_MATRIX.md      ← Feature Registry (@influenceos/contracts)
 *   docs/MOBILE_READINESS.md    ← Feature Registry
 *   docs/SOCIAL_PROVIDER_MATRIX.md ← provider capability matrix (@influenceos/shared)
 *
 * Run with: pnpm docs:generate
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { FEATURES, computeCoverage, listApiEndpoints } from '@influenceos/contracts';
import { CAPABILITY_MATRIX, PLATFORMS, PLATFORM_META } from '@influenceos/shared';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const docsDir = join(root, 'docs');
mkdirSync(docsDir, { recursive: true });

const check = (b: boolean) => (b ? '✅' : '—');
const stamp = '<!-- GENERATED by tools/generate-docs.mts — run `pnpm docs:generate`. Do not edit by hand. -->';

// --- FEATURE_MATRIX.md ------------------------------------------------------
function featureMatrix(): string {
  const rows = FEATURES.map(
    (f) =>
      `| ${f.name} | ${f.module} | ${f.classification} | ${f.apiStatus} | ${f.webStatus} | ${check(f.mobileReady)} | ${f.permissions.join(', ')} | ${f.flag ?? '—'} |`,
  ).join('\n');
  const cov = computeCoverage();
  return `# Feature Matrix

${stamp}

Every major capability, its backend/API/web status, and whether it is **Mobile Ready**
(business logic server-side, documented API, server-side auth + permissions, stable
contracts, media represented independently of the web UI — spec addendum §37).

**Coverage:** ${cov.total} features · API ready ${cov.apiReady} · Web ready ${cov.webReady} · Mobile ready ${cov.mobileReady} · Admin-desktop-only ${cov.adminOnly} · **Mobile readiness ${cov.mobileReadinessPercent}%** (of SHARED features).

| Feature | Module | Class | API | Web | Mobile Ready | Roles | Flag |
|---|---|---|---|---|:---:|---|---|
${rows}

## API endpoints by feature

${FEATURES.map((f) => `### ${f.name}\n\n${f.apiEndpoints.map((e) => `- \`${e}\``).join('\n')}`).join('\n\n')}
`;
}

// --- MOBILE_READINESS.md ----------------------------------------------------
function mobileReadiness(): string {
  const cov = computeCoverage();
  const shared = FEATURES.filter((f) => f.classification === 'SHARED');
  const admin = FEATURES.filter((f) => f.classification !== 'SHARED');
  const line = (f: (typeof FEATURES)[number]) =>
    `| ${f.name} | ${check(f.apiStatus === 'READY')} | ${check(f.webStatus === 'READY')} | ${check(f.mobileReady)} | ${f.deepLink ?? '—'} |`;
  return `# Mobile Readiness

${stamp}

Purpose: guarantee that when the iOS/Android app is built, **nothing important lives
only in the web app**. The API is the product core; the web is one client.

**Mobile readiness: ${cov.mobileReadinessPercent}%** of SHARED features.

## Shared features (must be mobile-ready)

| Feature | API | Web | Mobile Ready | Deep Link |
|---|:---:|:---:|:---:|---|
${shared.map(line).join('\n')}

## Admin / desktop-only by design

These are intentionally not exposed to mobile (documented reason: technical
administration surface).

| Feature | API | Web | Mobile Ready | Deep Link |
|---|:---:|:---:|:---:|---|
${admin.map(line).join('\n')}

## Definition of "Mobile Ready"

1. Business logic exists server-side · 2. API endpoint exists · 3. API documented ·
4. Auth works through the API · 5. Permissions enforced server-side ·
6. Request/response contracts stable · 7. Media represented independently of web UI ·
8. Filtering/pagination server-side · 9. API tests exist · 10. No web-only server behavior.

Total documented endpoints: ${listApiEndpoints().length}.
`;
}

// --- SOCIAL_PROVIDER_MATRIX.md ---------------------------------------------
function providerMatrix(): string {
  const rows = PLATFORMS.map((p) => {
    const m = CAPABILITY_MATRIX[p];
    return `| ${PLATFORM_META[p].label} | ${m.profileLookup} | ${m.followerSync} | ${m.contentLookup} | ${m.contentEmbed} | ${m.contentMetrics} | ${m.availabilityMonitoring} | ${m.requiresCreatorAuthorization ? 'Yes' : 'No'} | ${m.requiresAppAuthorization ? 'Yes' : 'No'} | Yes |`;
  }).join('\n');
  const notes = PLATFORMS.map((p) => `### ${PLATFORM_META[p].label}\n\n${CAPABILITY_MATRIX[p].notes}`).join('\n\n');
  return `# Social Provider Matrix

${stamp}

Capabilities reflect current official platform documentation and the fact that this
product **does not ask influencers to authorize their accounts** (no creator OAuth),
so several profile-sync capabilities are authorization-dependent and the product leans
on strong manual fallbacks + official content embeds. A manual fallback ALWAYS exists.

Legend: \`YES\` always · \`YES_WITH_API\` needs the official API credential ·
\`CONDITIONAL\` depends on account type/eligibility · \`AUTHORIZATION_DEPENDENT\`
needs creator/app OAuth we don't perform · \`MANUAL\` manual only · \`NO\` unsupported.

| Platform | Profile Lookup | Follower Sync | Content Lookup | Content Embed | Content Metrics | Availability | Creator Auth | App Auth | Manual Fallback |
|---|---|---|---|---|---|---|:---:|:---:|:---:|
${rows}

## Notes & limitations

${notes}
`;
}

writeFileSync(join(docsDir, 'FEATURE_MATRIX.md'), featureMatrix());
writeFileSync(join(docsDir, 'MOBILE_READINESS.md'), mobileReadiness());
writeFileSync(join(docsDir, 'SOCIAL_PROVIDER_MATRIX.md'), providerMatrix());
console.log('Generated docs/FEATURE_MATRIX.md, docs/MOBILE_READINESS.md, docs/SOCIAL_PROVIDER_MATRIX.md');
